server:
  port: 8080

spring:
  cloud:
    client:
      hostname: localhost
  application:
    name: simpleapiservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadata-map:
      metadataEntry: "entry"
