logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator: #configures the discovery client route locator

          enabled: true # Enable RouteLocator to take from DiscoveryClient compliant registry (Eureka)

    loadbalancer:
      configurations: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: '*'